model:
  _target_: src.models.LSTP_TG_blip2_module.LSTPSFModule
  model_name_or_path: ckpts/blip2-flan-t5-xl
  sampler_name_or_path: ckpts/bert-base-uncased
  of_extractor_name_or_path: ckpts/raft/raft-sintel.pth
  temperature: 1.0
  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 5.0e-05
    weight_decay: 0.05
  scheduler: cosine
  scheduler_params:
    warmup_steps: 0.05
  generate_configs:
    length_penalty: 1
    repetition_penalty: 1.5
    num_beams: 5
    min_length: 1
    max_length: 250
    top_p: 0.9
    temperature: 0.8
model/params/total: 4073211655
model/params/trainable: 4073146119
model/params/non_trainable: 65536
data:
  _target_: src.data.videoinstruct_datamodule.VIDEOINSTRUCTDataModule
  text_dir: ${paths.text_dir}
  video_dir: ${paths.video_dir}
  of_dir: ${paths.of_dir}
  nframe: 4
  processor_name: ckpts/blip2-flan-t5-xl
  sampler_processor_name: ckpts/bert-base-uncased
  target_size: 224
  batch_size: 32
  num_workers: 0
  pin_memory: false
trainer:
  _target_: lightning.pytorch.trainer.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 3
  accelerator: gpu
  devices: 1
  check_val_every_n_epoch: 1
  deterministic: false
callbacks:
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ${paths.output_dir}/checkpoints
    filename: epoch_{epoch:03d}
    monitor: val/iou_score
    verbose: false
    save_last: true
    save_top_k: 1
    mode: max
    auto_insert_metric_name: false
    save_weights_only: false
    every_n_train_steps: null
    train_time_interval: null
    every_n_epochs: null
    save_on_train_epoch_end: null
  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: val/iou_score
    min_delta: 0.0
    patience: 100
    verbose: false
    mode: max
    strict: true
    check_finite: true
    stopping_threshold: null
    divergence_threshold: null
    check_on_train_epoch_end: null
  model_summary:
    _target_: lightning.pytorch.callbacks.RichModelSummary
    max_depth: 2
extras:
  ignore_warnings: true
  enforce_tags: false
  print_config: true
task_name: train
tags:
- LSTP_TG
- videoinstruct
- flant5xl
- blip2
ckpt_path: null
seed: 43
