_target_: src.models.LSTP_SF_small_module.LSTPSFModule

model_name_or_path: "ckpts/instructblip-flan-t5-xl"
# model_name_or_path: "ckpts/instructblip-vicuna-7b"
sampler_name_or_path: "ckpts/bert-base-uncased"
of_extractor_name_or_path: "ckpts/raft/raft-sintel.pth"

temperature: 1.0

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00001
  weight_decay: 0.05

# optimizer:
#   _target_: torch.optim.AdamW
#   _partial_: True
#   lr: 0.00001
#   eps: 0.00000001
#   betas: (0.9, 0.98)

# scheduler:
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.8
#   patience: 10

scheduler: cosine
scheduler_params:
  warmup_steps: 0.05


# scheduler:
#   _target_: torch.optim.lr_scheduler.

generate_configs:
  length_penalty: 1 
  repetition_penalty: 1.5
  num_beams: 5
  min_length: 1
  max_length: 250
  top_p: 0.9
  temperature: 0.8